# Generated by Django 4.1.4 on 2023-05-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_bankdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='combinedData',
        ),
        migrations.DeleteModel(
            name='PcMastercard',
        ),
        migrations.DeleteModel(
            name='PebblesBank',
        ),
        migrations.DeleteModel(
            name='PebblesCredit',
        ),
        migrations.DeleteModel(
            name='RbcBank',
        ),
        migrations.DeleteModel(
            name='RbcVisa',
        ),
        migrations.AlterModelOptions(
            name='bankdata',
            options={'managed': False},
        ),
    ]
