# Generated by Django 4.1.4 on 2023-06-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_delete_combineddata_delete_pcmastercard_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankdata',
            table='bankapp_bankdata',
        ),
    ]
